# Generated by Django 5.2.4 on 2025-08-01 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('couleur', models.CharField(blank=True, help_text='Format: #FFFFFF', max_length=7, null=True)),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône", max_length=50, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='boutique.categorie')),
            ],
            options={
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('code_sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, help_text='Prix fixe du produit (optionnel)', max_digits=10, null=True)),
                ('prix_libre', models.BooleanField(default=False, help_text="Autoriser la saisie d'un prix libre à la vente")),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('gestion_stock', models.BooleanField(default=True)),
                ('stock_actuel', models.PositiveIntegerField(default=0)),
                ('stock_minimum', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(related_name='produits', to='boutique.categorie')),
            ],
        ),
    ]
