# Generated by Django 5.2.4 on 2025-08-10 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création de la vente')),
                ('date_cloture', models.DateTimeField(blank=True, help_text='Date et heure de clôture de la vente', null=True)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('cloture', 'Clôturée'), ('archive', 'Archivée')], default='attente', help_text='État actuel de la vente', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Montant total de la vente en euros', max_digits=10)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('vendeur', models.ForeignKey(help_text='Vendeur qui a effectué la transaction', on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Detailvente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, help_text='quantité vendue')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix unitaire au moment de la vente', max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits_vendus', to='boutique.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='boutique.vente')),
            ],
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['vendeur', 'date_creation'], name='boutique_ve_vendeur_29e297_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['statut'], name='boutique_ve_statut_8c7648_idx'),
        ),
    ]
